**Week 1 Assignment**

Dataset: (Shopping Dataset)
The dataset is distributed across multiple category-wise CSV files.
For easier analysis, all files will first be combined into a single dataset.

In [0]:
import pandas as pd
import os

Only CSV files are required for this assignment, so I filtered them separately.

In [0]:
folder_path = "/Workspace/Users/srithankodumuru22@gmail.com/DbAcademy/shopping_data"
all_f = os.listdir(folder_path)
csv_f= []

for file_name in all_f:
    if file_name.endswith(".csv"):
        csv_f.append(file_name)

print("CSV files found :", len(csv_f))

CSV files found : 98

I combined all CSV files into a single dataframe.

In [0]:
all_products = []

for file_name in csv_f:
    current_path = os.path.join(folder_path,file_name)
    current_frame = pd.read_csv(current_path)
    current_frame["source_category"] = file_name.replace(".csv", "")
    all_products.append(current_frame)

shopping_data = pd.concat(all_products,ignore_index=True)
print("Combined dataset shape:", shopping_data.shape)

Combined dataset shape: (2000, 25)

I explored the dataset to understand its structure.

In [0]:
shopping_data.head()

   product_id  ...          source_category
0    14487194  ...  shampoo-and-conditioner
1    14472340  ...  shampoo-and-conditioner
2    16779444  ...  shampoo-and-conditioner
3    15880308  ...       shaving-essentials
4    18947596  ...                   shorts

[5 rows x 25 columns]

In [0]:
shopping_data.tail()

      product_id     title  ...   category   source_category
1995    13698258     KREDO  ...    watches  Combined_dataset
1996    16896006     GUESS  ...    watches  Combined_dataset
1997     1708108  GIORDANO  ...    watches  Combined_dataset
1998    19280114  Fastrack  ...    watches  Combined_dataset
1999    18601682   BOLDFIT  ...  yoga-mats  Combined_dataset

[5 rows x 25 columns]

In [0]:
shopping_data.shape

(2000, 25)

In [0]:
shopping_data.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category', 'source_category'],
      dtype='object')

In [0]:
shopping_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2000 non-null   int64
 1   title                   2000 non-null   object
 2   product_description     2000 non-null   object
 3   rating                  2000 non-null   float64
 4   ratings_count           2000 non-null   int64
 5   initial_price           2000 non-null   float64
 6   discount                1758 non-null   float64
 7   final_price             2000 non-null   object
 8   currency                2000 non-null   object
 9   images                  2000 non-null   object
 10  delivery_options        2000 non-null   object
 11  product_details         2000 non-null   object
 12  breadcrumbs             2000 non-null   object
 13  product_specifications  2000 non-null   object
 14  amount_of_stars         2000 non-null   object
 15  what_customers_said     854 non-null    object
 16  seller_name             1398 non-null   object
 17  sizes                   2000 non-null   object
 18  videos                  438 non-null    object
 19  seller_information      1398 non-null   object
 20  variations              876 non-null    object
 21  best_offer              2000 non-null   object
 22  more_offers             2000 non-null   object
 23  category                2000 non-null   object
 24  source_category         2000 non-null   object
dtypes: float64(3), int64(2), object(20)
memory usage: 390.8+ KB

Checking for missing values before performing operations

In [0]:
shopping_data.isnull().sum().sort_values(ascending=False)

videos                    1562
what_customers_said       1146
variations                1124
seller_information         602
seller_name                602
discount                   242
product_id                   0
product_specifications       0
category                     0
more_offers                  0
best_offer                   0
sizes                        0
amount_of_stars              0
breadcrumbs                  0
title                        0
product_details              0
delivery_options             0
images                       0
currency                     0
final_price                  0
initial_price                0
ratings_count                0
rating                       0
product_description          0
source_category              0
dtype: int64

Most missing values were found in only a few columns.
For numerical columns, I replaced missing values using the median.

In [0]:
numeric_columns = shopping_data.select_dtypes(include="number").columns

for column in numeric_columns:
    shopping_data[column] = (
        shopping_data[column].fillna(shopping_data[column].median())
    )

Handling duplicate records

In [0]:
count = shopping_data.duplicated().sum()
print("Duplicate rows found:", count)

if count > 0:
    shopping_data = shopping_data.drop_duplicates()
    print("Duplicates removed")
else:
    print("No duplicate records were found")

Duplicate rows found: 0
No duplicate records were found

Performing a few operations such as filtering rows and selecting.

In [0]:
shopping_data[shopping_data["rating"] >= 4.5].head()

   product_id  ...          source_category
2    16779444  ...  shampoo-and-conditioner
3    15880308  ...       shaving-essentials
4    18947596  ...                   shorts
5    18946864  ...                   shorts
6    18921438  ...                   shorts

[5 rows x 25 columns]

In [0]:
shopping_data[["title","final_price","rating"]].head()

                            title  final_price  rating
0                Lotus Botanicals    "₹247.00"     4.0
1                    Earth Rhythm    "₹284.00"     4.1
2  FIXDERMA COSMETIC LABORATORIES  "₹1,250.00"     4.8
3                          Sirona    "₹285.00"     4.9
4                       KASSUALLY    "₹593.00"     4.7

Creating a new feature called popularity_score.

This feature combines product rating and the number of ratings received. A product with a high rating and many reviews is generally considered more reliable.

In [0]:
shopping_data["popularity_score"] = (
    shopping_data["rating"] * shopping_data["ratings_count"]
)

The popularity_score makes it easy to spot products that not only have high ratings, but are also trusted by many customers based on the number of reviews.

In [0]:
output_path = ("/Workspace/Users/srithankodumuru22@gmail.com/DbAcademy/cleaned_shopping_dataset.csv")

shopping_data.to_csv(output_path, index=False)
print("Dataset saved successfully")

Dataset saved successfully

**Summary**

Initially, the dataset was available as multiple category-wise CSV files.
To make the analysis easier, all files were combined into a single dataframe.
After combining the data, I explored the dataset structure, checked the available columns and reviewed the data types. Missing values and duplicate records were also examined as part of the cleaning process.

As an additional step, I created a new feature called popularity_score using the product rating and the number of ratings. This helped in identifying products that are both highly rated and frequently reviewed.

The final cleaned dataset was then exported for future analysis.